version: "3.3"
services:
  page-www-example-com:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/snippets/:/etc/nginx/snippets/
      - ./ssl/:/etc/ssl/
